time_stretch/blog/urls.py
from django.conf.urls import url, patterns
from blog import views
from feeds import EntryFeed

urlpatterns = patterns(
    '',
    url(r'^$', views.EntryListView.as_view(), name='index'),
    url(
        r'^entry/(?P<entry_id>[0-9]*)/$',
        views.EntryDetailView.as_view(),
        name='entry'
    ),
    url(r'^rss/$', EntryFeed(), name='entry_feed'),
)

time_stretch/time_stretch/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  # noqa
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),
    url(r'^mtg/$',
        TemplateView.as_view(template_name='pages/mtg_charts.html'),
        name="mtg"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),


    # Your stuff: custom urls go here
    url(r'^blog/$', include('blog.urls', namespace='blog')),
    url(
        r'^styles/$',
        TemplateView.as_view(template_name='pages/bootstrap_test.html'),
        name='styles'
    ),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

time_stretch/blog/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from .fields import AutoDatetimeField
from .managers import (
    PublicManager,
    LoginManager,
    PrivateManager,
    )


# Create your models here.
class Entry(models.Model):
    PUBLIC = 0
    LOGIN = 1
    PRIVATE = 2
    PUBLICITIES = (
        (PUBLIC, 'Public'),
        (LOGIN, 'Login'),
        (PRIVATE, 'Private'),
    )

    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200, default='')  # RSS
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    modified = AutoDatetimeField(default=timezone.now)
    publicity = models.IntegerField(choices=PUBLICITIES, default=PRIVATE)

    class Meta:
        verbose_name_plural = 'entries'

    objects = models.Manager()
    public = PublicManager()
    login = LoginManager()
    private = PrivateManager()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:entry', kwargs={'entry_id': str(self.id)})

time_stretch/blog/views.py
# from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Entry


class EntryListView(ListView):

    def get_queryset(self):
        if self.request.user.is_superuser:
            qs = Entry.private.all()

        elif self.request.user.is_authenticated():
            qs = Entry.login.all()

        else:
            qs = Entry.public.all()
        return qs.order_by('-created')


class EntryDetailView(DetailView):
    model = Entry
    pk_url_kwarg = 'entry_id'

    def get_object(self):
        pk = int(self.kwargs.get(self.pk_url_kwarg, None))
        print pk
        if self.request.user.is_superuser:
            return Entry.private.get(pk=pk)

        elif self.request.user.is_authenticated():
            return Entry.login.get(pk=pk)

        else:
            return Entry.public.get(pk=pk)

time_stretch/blog/templates/blog/_entry.html
<div class='col-md-12'>
    <div class='blog-entry'>
    <h1 class='entry-title'>
        <a href="{% url "blog:entry" entry_id=entry.id %}">{{entry.title}}</a>
        <small>{{entry.description}}</small>
    </h1>
    <p>{{entry.content|safe}}</p>
    <p class='entry-info'>{{entry.created}}</p>
    </div>
</div>

time_stretch/blog/templates/blog/entry_detail.html
{% extends "base.html" %}

{% block content %}
{% include "blog/_entry.html" %}
{% endblock content %}

time_stretch/blog/templates/blog/entry_list.html
{% extends "base.html" %}

{% block content %}
    <div class='row' id='entry-list'>
    {% for entry in entry_list %}
        {% include "blog/_entry.html" %}
    {% endfor %}
    </div>
{% endblock content %}

time_stretch/templates/base.html
{% load staticfiles i18n %}
{% load pipeline %}
<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Time Stretch{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    {% comment %}

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    {% endcomment %}
    {% stylesheet 'all' %}

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    {# <link href="{% static 'css/project.css' %}" rel="stylesheet"> #}
    {% endblock %}
    {% block extra_css %}
    {% endblock extra_css %}

    {% block angular %}
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.min.js"></script>
    {% endblock %}

  </head>

  <body>

    <div class="header navbar navbar-inverse">
      <div class="container">
        <a class="navbar-brand" href="/">Time Stretch</a>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'blog:index' %}">Blog</a></li>
        </ul>
      </div>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Ben's personal site.  Nothing to see here yet.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="//cdnjs.cloudflare.com/ajax/libs/d3/2.10.0/d3.v2.min.js "></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      {% javascript 'all' %}


      <!-- place project specific Javascript in this file -->

    {% block extra_js %}
    {% endblock extra_js %}

    {% endblock javascript %}
  </body>
</html>

time_stretch/templates/pages/about.html
{% extends "base.html" %}

time_stretch/templates/pages/home.html
{% extends "base.html" %}

time_stretch/templates/pages/tutorials.html
{% extends "base.html" %}
https://www.docker.com/tryit/
http://pcottle.github.io/learnGitBranching/?demo
http://flukeout.github.io/
http://latentflip.com/loupe
http://bost.ocks.org/mike/selection/